---
- name: play1
  hosts: localhost
  tasks:
  - name: play1-Task1
    debug:
      msg:
       - "Welcome to ansible playbook. This is task1 of first play"

  - name: play1-Task2
    debug:
      msg:
       - "This is the second task of the same play"

- name: play2
  hosts: localhost
  tasks:
  - name: play2-task1
    debug:
      msg:
       - "This is task1 of play 2"
...
