---
- hosts: 192.168.56.102
  gather_facts: no
  become: yes
  tasks:
  - name: Installing apache2 server
    package: name={{ item }} update_cache=yes state=latest
    loop: [ 'apache2', 'vim', 'screen' ]
    tags: [ 'install' ]

  - name: Copying index.html file
    copy: 
      src: /home/vagrant/playbooks/apache2/index.html
      dest: /var/www/html
      owner: root
      group: root
      mode: '0644'
    tags: [ 'update', 'sync' ]    

  - name: Starting the services
    service: 
      name: apache2
      state: started
      enabled: yes
    tags: [ 'service' ]

  - name: Changing Apache port to 8080
    lineinfile:
      path: /etc/apache2/ports.conf
      regexp: '^Listen '
      insertafter: '^#Listen '
      line: Listen 8080
    notify: Restart apache2
    tags: [ 'update1', 'sync' ]
  
  handlers: 
  - name: Restart apache2
    service:
      name: apache2
      state: restarted 

...
