---
- hosts: 192.168.56.102
  gather_facts: no
  become: yes
  tasks:
  - name: Installing apache2 server
    package: name=apache2 update_cache=yes state=latest

  - name: Copying index.html file
    copy: src=/home/vagrant/playbooks/apache2/index.html dest=/var/www/html owner=root group=root mode='0644'

  - name: Starting the services
    service: name=apache2 state=started enabled=yes
...
