---
- name: Usage of logical operators
  hosts: localhost
  vars:
    list: [10, 20, 30]
    x: 10
    y: 15
  tasks:
  - name: checking logical operations
    debug:
      msg:
        - "Value of x is {{ x }} and value of y is {{ y }}"
        - "Checking if x is in list {{ x in list }}"
        - "Checking if y is in list {{ y in list }}"
        - "Checking if both x and y are in list {{ x in list and y in list }}"
        - "Checking if either x or y is in list {{ x in list or y in list }}"
        - "x < y and x in list {{ x < y and x in list }}"
        - "x > y and x in list {{ x > y and x in list }}"
...
